---

- hosts: local
  user: ska
  sudo: yes

  vars_files:
    - group_vars/secretvars.yml

  roles:
    - { role: angstwad.docker_ubuntu, docker_group_members: ["ska"], docker_opts: '-g /data/docker --insecure-registry registry.dev-tools.msgc.gcba' }
    - common
    - dotfiles
    - ssh
    - git
    - fish
    - i3gaps
    - google-chrome
